FROM eclipse-temurin:17-jdk-alpine

WORKDIR /app

COPY .mvn/ .mvn
COPY mvnw pom.xml ./
RUN chmod +x mvnw && ./mvnw dependency:go-offline

COPY src ./src
RUN ./mvnw clean package -DskipTests

ENV PORT=8080
EXPOSE 8080

ENTRYPOINT ["sh", "-c", "java -jar target/demo-0.0.1-SNAPSHOT.jar --server.port=${PORT}"]
