spring.application.name=demo
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/expensedb
spring.datasource.username=root
spring.datasource.password=@Yash7732

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true