spring.application.name=demo

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://sql12.freesqldatabase.com:3306/sql12826031}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sql12826031}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:PsXaFisCWR}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.hikari.maximum-pool-size=1
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.web.resources.static-locations=classpath:/static/

server.port=${PORT:8081}

app.admin.username=${APP_ADMIN_USERNAME:admin}
app.admin.password=${APP_ADMIN_PASSWORD:admin123}